format = """
$username\
$hostname\
$directory\
$cmd_duration\
$line_break\
$python\
$character"""


[character]
success_symbol = "[➜](#a7c080)"
error_symbol = "[➜](#e67e80)"
vimcmd_symbol = "[←](#7fbbb3)"


[cmd_duration]
format = "[$duration]($style) "
style = "#dbbc7f"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
